<table width=780 height=46 border=0 cellspacing=0 cellpadding=0>
<tr><td height=6 colspan=2>

<? if($page=="home") { ?>

<img src="img/sp.gif" width=780 height=6></td></tr>
<tr><td height=40 background="img/blue.gif" align=right valign=center class="text10w">
<? include "footeraddr.inc"; ?>
</td><td width=20><img src="img/blue.gif" height=40 width=20>

<? } else { ?>

<img src="../img/sp.gif" width=780 height=6></td></tr>
<tr><td height=40 background="../img/blue.gif" align=right valign=center class="text10w">
<? include "footeraddr.inc"; ?>
</td><td width=20><img src="../img/blue.gif" height=40 width=20>

<? } ?>

</td></tr>
</table>