
<strong>
<a href="index.php" <? if ($page=="aviators") print("style='color:blue'"); ?>>Little Aviators</a><br><br>
<a href="staff.php" <? if ($page=="aviators_staff") print("style='color:blue'"); ?>>Staff</a><br><br>
<a href="board.php" <? if ($page=="aviators_board") print("style='color:blue'"); ?>>Board of Directors</a><br><br>
<a href="pictures.php" <? if ($page=="aviators_pictures") print("style='color:blue'"); ?>>Pictures</a><br><br>
<a href="directions.php" <? if ($page=="aviators_directions") print("style='color:blue'"); ?>>Directions</a><br><br>
<a href="waitlist.php" <? if ($page=="aviators_waitlist") print("style='color:blue'"); ?>>Waitlist</a><br><br>
<a href="rates.php" <? if ($page=="aviators_rates") print("style='color:blue'"); ?>>Rates and Fees</a><br>
</strong>
