
<strong>
<a href="index.php" <? if ($page=="enrollment") print("style='color:blue'"); ?>>Enrollment</a><br><br>
<a href="tours.php" <? if ($page=="enrollment_tours") print("style='color:blue'"); ?>>Tours & Events</a><br><br>
<a href="tuition.php" <? if ($page=="enrollment_tuition") print("style='color:blue'"); ?>>Tuition</a><br><br>
<a href="faq.php" <? if ($page=="enrollment_faq") print("style='color:blue'"); ?>>Frequently Asked Questions</a><br>
</strong>
