
<strong>
<a href="index.php" <? if ($page=="about") print("style='color:blue'"); ?>>About GeoKids</a><br><br>
<a href="mission.php" <? if ($page=="about_mission") print("style='color:blue'"); ?>>Mission</a><br><br>
<a href="staff.php" <? if ($page=="about_staff") print("style='color:blue'"); ?>>Staff</a><br><br>
<a href="board.php" <? if ($page=="about_board") print("style='color:blue'"); ?>>Board of Directors</a><br><br>
<a href="campus.php" <? if ($page=="about_campus") print("style='color:blue'"); ?>>Campus Pictures</a><br><br>
<a href="values.php" <? if ($page=="about_values") print("style='color:blue'"); ?>>Our Values</a><br><br>
<a href="directions.php" <? if ($page=="about_directions") print("style='color:blue'"); ?>>Directions</a><br><br>
<a href="calendar.php" <? if ($page=="about_calendar") print("style='color:blue'"); ?>>Calendar</a><br><br>
</strong>
