
<strong>
<a href="index.php" <? if ($page=="aviators") print("style=\"color:red\""); ?>>Little Aviators</a><br><br>
<a href="staff.php" <? if ($page=="aviators_staff") print("style=\"color:red\""); ?>>Staff</a><br><br>
<a href="board.php" <? if ($page=="aviators_board") print("style=\"color:red\""); ?>>Board of Directors</a><br><br>
<a href="values.php" <? if ($page=="aviators_values") print("style=\"color:red\""); ?>>Our Values</a><br><br>
<a href="directions.php" <? if ($page=="aviators_directions") print("style=\"color:red\""); ?>>Directions</a><br><br>
<? /* ?> <a href="pictures.php" <? if ($page=="aviators_pictures") print("style=\"color:red\""); ?>>Pictures</a><br><br>
<a href="waitlist.php" <? if ($page=="aviators_waitlist") print("style=\"color:red\""); ?>>Waitlist</a><br><br>
<a href="rates.php" <? if ($page=="aviators_rates") print("style=\"color:red\""); ?>>Rates and Fees</a><br> <? */ ?>
</strong>
