
<strong>
<a href="index.php" <? if ($page=="inside_learning") print("style=\"color:red\""); ?>> Learning</a><br><br>
<a href="reggio.php" <? if ($page=="inside_reggio") print("style=\"color:red\""); ?>>Reggio Principles</a><br><br>
<a href="accreditation.php" <? if ($page=="inside_accreditation") print("style=\"color:red\""); ?>>NAEYC Accreditation</a><br><br>
<a href="parent.php" <? if ($page=="inside_parent") print("style=\"color:red\""); ?>>Parent Education</a><br>
</strong>
