
<strong>
<a href="index.php" <? if ($page=="inside") print("style='color:blue'"); ?>>Classrooms</a><br><br>
<a href="learning.php" <? if ($page=="inside_learning") print("style='color:blue'"); ?>>Learning at GeoKids</a><br><br>
<a href="reggio.php" <? if ($page=="inside_reggio") print("style='color:blue'"); ?>>Reggio Principles</a><br><br>
<a href="accreditation.php" <? if ($page=="inside_accreditation") print("style='color:blue'"); ?>>NAEYC Accreditation</a><br><br>
<a href="parent.php" <? if ($page=="inside_parent") print("style='color:blue'"); ?>>Parent Education</a><br>
</strong>
