<? if($page=="home") { ?>

<table width=780 height=46 border=0 cellspacing=0 cellpadding=0>
<tr><td height=6 colspan=2><img src="img/sp.gif" width=780 height=6></td></tr>
<tr><td height=40 background="img/teal.gif" align=right valign=center class="text10w"><strong>GeoKids</strong>, 345 Middlefield Road, Mail Stop 204, Menlo Park, CA  94025<br>
<strong>Phone:</strong> (650) 329-4236 | <strong>Fax:</strong> (650) 329-4200</td><td width=20><img src="img/teal.gif" height=40 width=20></td></tr>
</table>

<? } else { ?>

<table width=780 height=46 border=0 cellspacing=0 cellpadding=0>
<tr><td height=6 colspan=2><img src="../img/sp.gif" width=780 height=6></td></tr>
<tr><td height=40 background="../img/teal.gif" align=right valign=center class="text10w"><strong>GeoKids</strong>, 345 Middlefield Road, Mail Stop 204, Menlo Park, CA  94025<br>
<strong>Phone:</strong> (650) 329-4236 | <strong>Fax:</strong> (650) 329-4200</td><td width=20><img src="../img/teal.gif" height=40 width=20></td></tr>
</table>

<? } ?>