<title>GeoKids Early Childhood Development Center</title>
	<link rel=stylesheet type="text/css" href="<? if($page!="home") print("../"); ?>styles.css">
	<link type="text/plain" rel="author" href="/humans.txt" />
	<META NAME="robots" CONTENT="index, follow">
	<META NAME="Description" CONTENT="Early Childhood Development Center, Menlo Park, CA."> 
	<META NAME="Keywords" CONTENT="childhood development, pre-school, day care, geokids">
