
<strong>
<a href="index.php" <? if ($page=="enrollment") print("style=\"color:red\""); ?>>Enrollment</a><br><br>
<a href="tours.php" <? if ($page=="enrollment_tours") print("style=\"color:red\""); ?>>Tours & Events</a><br><br>
<a href="tuition.php" <? if ($page=="enrollment_tuition") print("style=\"color:red\""); ?>>Tuition</a><br><br>
<a href="faq.php" <? if ($page=="enrollment_faq") print("style=\"color:red\""); ?>>Frequently Asked Questions</a><br>
</strong>
