
<strong>
<a href="index.php" <? if ($page=="about") print("style=\"color:red\""); ?>>Curriculum</a><br><br>
<a href="mission.php" <? if ($page=="about_mission") print("style=\"color:red\""); ?>>Mission</a><br><br>
<a href="staff.php" <? if ($page=="about_staff") print("style=\"color:red\""); ?>>Staff</a><br><br>
<a href="board.php" <? if ($page=="about_board") print("style=\"color:red\""); ?>>Board of Directors</a><br><br>
<a href="campus.php" <? if ($page=="about_campus") print("style=\"color:red\""); ?>>Campus Pictures</a><br><br>
<a href="values.php" <? if ($page=="about_values") print("style=\"color:red\""); ?>>Our Values</a><br><br>
<a href="directions.php" <? if ($page=="about_directions") print("style=\"color:red\""); ?>>Directions</a><br>
</strong>
